services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  app:
    image: node:20-alpine
    command: sh -c "sleep 5; yarn install && yarn run start"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=mongodb://root:example@mongo:27017/
volumes:
  app-mongodb-data:
